language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - hhvm
  - nightly

allow_failures:
  -php: nightly
  -php: hhvm

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction --no-progress

script:
   - mysql -e 'create database algolia;' -uroot
   - 'php vendor/bin/phpunit --testsuite=unit;'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then php vendor/bin/phpunit --testsuite=integration; fi'
